### PR TITLE
Add graceful shutdown of HTTP server

### PR DESCRIPTION
**Pull request by brycekahle**
**- Summary**

This allows the server to finish in-progress requests before stopping.

**- Test plan**

Local testing with Ctrl-C.

**- Description for the changelog**

Add graceful shutdown of server in response to SIGINT and SIGTERM.

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by rybit** [comment]
Do you think it might we worth integrating with netlify-commons? We haven't yet b/c the library didn't exist at the time.

**Comment by brycekahle** [comment]
For things like this? Sure. Some of the other packages feel netlify-specific.

**Comment by rybit** [comment]
I think that this, configuration and logging would be good to unify. Mostly b/c this has an old copy paste version of that code.

**Comment by brycekahle** [comment]
Updated to use commons.

**Pull request merged**
