### PR TITLE
travis: update go version

### PR DESCRIPTION
**Pull request by dvrkps**

### CODE REVIEW

**Comment by brycekahle** [comment]
@dvrkps Thanks for this. We like to keep the go version on Travis in sync with the version in Docker. Currently that is still 1.8.3. I'll check with the team about getting that upgraded to 1.9.

**Comment by dvrkps** [comment]
@brycekahle can i close this ?

**Comment by brycekahle** [comment]
If you wish. I was keeping it open as a reminder to upgrade to Go 1.9.

**Comment by dvrkps** [comment]
@brycekahle ok, stay open.

**Pull request closed without merging**
